<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="yed" nsURI="http://www.eclipse.org/epsilon/emc/yed" nsPrefix="">
  <eAnnotations source="emf.gen">
    <details key="basePackage" value="org.eclipse.epsilon.emc"/>
    <details key="modelDirectory" value="/org.eclipse.epsilon.emc.yed/src-gen"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Graph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" upperBound="-1"
        eType="#//Slot" containment="true" eOpposite="#//Slot/owningNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//NodeType"
        eOpposite="#//NodeType/instances"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prototype" eType="#//SlotPrototype"
        eOpposite="#//SlotPrototype/slots"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningNode" eType="#//Node"
        eOpposite="#//Node/slots"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlotPrototype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningType" eType="#//NodeType"
        eOpposite="#//NodeType/slotPrototypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" upperBound="-1"
        eType="#//Slot" eOpposite="#//Slot/prototype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Node" eOpposite="#//Node/type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slotPrototypes" upperBound="-1"
        eType="#//SlotPrototype" containment="true" eOpposite="#//SlotPrototype/owningType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
        eType="#//NodeType" eOpposite="#//NodeType/subTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
        eType="#//NodeType" eOpposite="#//NodeType/superTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealType" eSuperTypes="#//PrimitiveType"/>
</ecore:EPackage>
