/* Generated By:JavaCC: Do not edit this line. BibtexTreeConstants.java Version 5.0 */
package org.eclipse.epsilon.emc.bibtex.parser.javacc;

public interface BibtexTreeConstants
{
  public int JJTBIBLIOGRAPHY = 0;
  public int JJTCOMMENT = 1;
  public int JJTPREAMBLE = 2;
  public int JJTSTRINGENTRY = 3;
  public int JJTPUBLICATIONENTRY = 4;
  public int JJTTAG = 5;
  public int JJTVOID = 6;


  public String[] jjtNodeName = {
    "Bibliography",
    "Comment",
    "Preamble",
    "StringEntry",
    "PublicationEntry",
    "Tag",
    "void",
  };
}
/* JavaCC - OriginalChecksum=3fd4f928c4e54936c7eb7b330b68db81 (do not edit this line) */
