/* Generated By:JJTree&JavaCC: Do not edit this line. BibtexConstants.java */
package org.eclipse.epsilon.emc.bibtex.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BibtexConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int COMMENT_START = 6;
  /** RegularExpression Id. */
  int PREAMBLE_START = 7;
  /** RegularExpression Id. */
  int STRING_START = 8;
  /** RegularExpression Id. */
  int COMMENT_ENTRY = 9;
  /** RegularExpression Id. */
  int OPEN_ENTRY = 11;
  /** RegularExpression Id. */
  int CLOSE_ENTRY = 12;
  /** RegularExpression Id. */
  int START_B_CONTENT = 14;
  /** RegularExpression Id. */
  int CLOSE_B_CONTENT = 15;
  /** RegularExpression Id. */
  int START_Q_CONTENT = 18;
  /** RegularExpression Id. */
  int CLOSE_Q_CONTENT = 19;
  /** RegularExpression Id. */
  int CONTENT_TEXT = 20;
  /** RegularExpression Id. */
  int ID = 21;
  /** RegularExpression Id. */
  int SEPARATOR = 22;
  /** RegularExpression Id. */
  int EQUALS = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_ENTRY = 1;
  /** Lexical state. */
  int IN_ENTRY_TYPE = 2;
  /** Lexical state. */
  int IN_COMMENT_ENTRY = 3;
  /** Lexical state. */
  int IN_PREAMBLE = 4;
  /** Lexical state. */
  int IN_BRACED_CONTENT = 5;
  /** Lexical state. */
  int IN_BRACED_NESTED_CONTENT = 6;
  /** Lexical state. */
  int IN_QUOTED_CONTENT = 7;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT>",
    "\"comment\"",
    "\"preamble\"",
    "\"string\"",
    "<COMMENT_ENTRY>",
    "<token of kind 10>",
    "\"{\"",
    "\"}\"",
    "<token of kind 13>",
    "\"{\"",
    "\"}\"",
    "\"{\"",
    "\"}\"",
    "\"\\\"\"",
    "\"\\\"\"",
    "<CONTENT_TEXT>",
    "<ID>",
    "\",\"",
    "\"=\"",
    "<NUMBER>",
    "\"#\"",
  };

}
