<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eol" nsURI="http://www.eclipse.org/epsilon/eol" nsPrefix="eol">
  <eAnnotations source="emf.gen">
    <details key="classPackageSuffix" value="metamodel.impl"/>
    <details key="utilityPackageSuffix" value="metamodel.util"/>
    <details key="metaDataPackageSuffix" value="metamodel"/>
    <details key="interfacePackageSuffix" value="metamodel"/>
    <details key="basePackage" value="org.eclipse.epsilon"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EolElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//EolElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" eType="#//TextRegion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextRegion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//TextPosition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//TextPosition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextPosition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EolProgram" eSuperTypes="#//EolLibraryModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedModules" upperBound="-1"
        eType="#//EolProgram" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imported" lowerBound="1"
        eType="#//StringExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedProgram" lowerBound="1"
        eType="#//EolLibraryModule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="#//EolElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedType" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorExpression" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperatorExpression" abstract="true"
      eSuperTypes="#//OperatorExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" eSuperTypes="#//PrimitiveExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DivideOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteralExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" lowerBound="1"
        eType="#//NameExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" lowerBound="1"
        eType="#//NameExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//ModelExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EqualsOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureCallExpression" abstract="true"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isArrow" eType="#//BooleanExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GreaterThanOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="GreaterThanOrEqualToOperatorExpression"
      eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImpliesOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerExpression" eSuperTypes="#//PrimitiveExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LessThanOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LessThanOrEqualToOperatorExpression"
      eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCallExpression" eSuperTypes="#//FeatureCallExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//NameExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedMethods" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MinusOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplyOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NameExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isType" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolvedContent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOperatorExpression" abstract="true"
      eSuperTypes="#//OperatorExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegativeOperatorExpression" eSuperTypes="#//UnaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotEqualsOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotOperatorExpression" eSuperTypes="#//UnaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlusOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyCallExpression" eSuperTypes="#//FeatureCallExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//NameExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extended" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealExpression" eSuperTypes="#//PrimitiveExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringExpression" eSuperTypes="#//PrimitiveExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//NameExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="create" eType="#//BooleanExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definitionPoints" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XorOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationDefinition" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextType" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotationBlock" eType="#//AnnotationBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//NameExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//FormalParameterExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="self" lowerBound="1" eType="#//VariableDeclarationExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="_result" eType="#//VariableDeclarationExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependingOperationDefinitions"
        upperBound="-1" eType="#//OperationDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BreakStatement" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BreakAllStatement" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContinueStatement" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deleted" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" lowerBound="1"
        eType="#//FormalParameterExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterated" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ExpressionOrStatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifBody" eType="#//ExpressionOrStatementBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBody" eType="#//ExpressionOrStatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returned" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//SwitchCaseExpressionStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//SwitchCaseDefaultStatement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchCaseStatement" abstract="true"
      eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ExpressionOrStatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ExpressionOrStatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelDeclarationStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//VariableDeclarationExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alias" upperBound="-1"
        eType="#//VariableDeclarationExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" lowerBound="1"
        eType="#//VariableDeclarationExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ModelDeclarationParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//ModelDeclarationStatement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FOLMethodCallExpression" eSuperTypes="#//FeatureCallExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" lowerBound="1"
        eType="#//FormalParameterExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//NameExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchCaseDefaultStatement" eSuperTypes="#//SwitchCaseStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchCaseExpressionStatement" eSuperTypes="#//SwitchCaseStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveExpression" abstract="true"
      eSuperTypes="#//LiteralExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionExpression" abstract="true"
      eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//CollectionInitValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentType" lowerBound="1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//LiteralExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetExpression" eSuperTypes="#//CollectionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagExpression" eSuperTypes="#//CollectionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceExpression" eSuperTypes="#//CollectionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedSetExpression" eSuperTypes="#//CollectionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MapExpression" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyValues" upperBound="-1"
        eType="#//KeyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//EolElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicTypes" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declared" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentType" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="#//UniqueCollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagType" eSuperTypes="#//CollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceType" eSuperTypes="#//OrderedCollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedSetType" eSuperTypes="#//OrderedCollectionType #//UniqueCollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="MapType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" lowerBound="1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyType" lowerBound="1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" abstract="true" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//NameExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutableAnnotation" eSuperTypes="#//Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleAnnotation" eSuperTypes="#//Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//StringExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValue" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialNameExpression" eSuperTypes="#//NameExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedModelDeclaration"
        upperBound="-1" eType="#//ModelDeclarationStatement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NativeType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nativeExpression" lowerBound="1"
        eType="#//StringExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelExpression" eSuperTypes="#//NameExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationBlock" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="simpleAnnotations" upperBound="-1"
        eType="#//SimpleAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executableAnnotations"
        upperBound="-1" eType="#//ExecutableAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelDeclarationParameter" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//NameExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//StringExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThrowStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thrown" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortStatement" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" upperBound="-1"
        eType="#//NameExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ExpressionOrStatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormalParameterExpression" eSuperTypes="#//VariableDeclarationExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionInitValue" abstract="true"
      eSuperTypes="#//EolElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExprList" eSuperTypes="#//CollectionInitValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="1"
        upperBound="-1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpRange" eSuperTypes="#//CollectionInitValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialAssignmentStatement" eSuperTypes="#//AssignmentStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" lowerBound="1"
        upperBound="-1" eType="#//ModelDeclarationStatement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NativeExpression" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nativeExpr" eType="#//StringExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isType" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreType" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoidType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelfType" eSuperTypes="#//PseudoType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelfContentType" eSuperTypes="#//PseudoType"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedCollectionType" eSuperTypes="#//CollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueCollectionType" eSuperTypes="#//CollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelfInnermostType" eSuperTypes="#//PseudoType"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationArgType" eSuperTypes="#//PseudoType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionOrStatementBlock" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EolLibraryModule" eSuperTypes="#//EolElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelDeclarations" upperBound="-1"
        eType="#//ModelDeclarationStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//OperationDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//NameExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
