<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml14" nsURI="uml14" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" lowerBound="1" upperBound="-1"
        eType="#//MultiplicityRange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" lowerBound="1"
        eType="#//Multiplicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcedureExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectSetExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IterationExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArgListsExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//VisibilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSpecification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//Namespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientDependency" upperBound="-1"
        eType="#//Dependency"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetFlow" upperBound="-1"
        eType="#//Flow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFlow" upperBound="-1"
        eType="#//Flow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" upperBound="-1"
        eType="#//Comment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateParameter" upperBound="-1"
        eType="#//TemplateParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" upperBound="-1"
        eType="#//Stereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValue" upperBound="-1"
        eType="#//TaggedValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityKind">
    <eLiterals name="vk_public"/>
    <eLiterals name="vk_protected" value="1"/>
    <eLiterals name="vk_private" value="2"/>
    <eLiterals name="vk_package" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        upperBound="-1" eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" lowerBound="1"
        upperBound="-1" eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="#//BooleanExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedElement" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotatedElement" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" lowerBound="1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultElement" eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stereotype" eSuperTypes="#//GeneralizableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definedTag" upperBound="-1"
        eType="#//TagDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotypeConstraint" upperBound="-1"
        eType="#//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralizableElement" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" upperBound="-1"
        eType="#//Generalization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" eType="#//GeneralizableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//GeneralizableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powertype" eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" eSuperTypes="#//GeneralizableElement #//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powertypeRange" upperBound="-1"
        eType="#//Generalization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownerScope" eType="#//ScopeKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScopeKind">
    <eLiterals name="sk_instance"/>
    <eLiterals name="sk_classifier" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagDefinition" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Stereotype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaggedValue" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElement" lowerBound="1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TagDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceValue" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeature" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeability" eType="#//ChangeableKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetScope" eType="#//ScopeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="#//OrderingKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeableKind">
    <eLiterals name="ck_changeable"/>
    <eLiterals name="ck_frozen" value="1"/>
    <eLiterals name="ck_addOnly" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OrderingKind">
    <eLiterals name="ok_unordered"/>
    <eLiterals name="ok_ordered" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationEnd" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="#//OrderingKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="#//AggregationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetScope" eType="#//ScopeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeability" eType="#//ChangeableKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="1"
        eType="#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" upperBound="-1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participant" lowerBound="1"
        eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" upperBound="-1"
        eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AggregationKind">
    <eLiterals name="ak_none"/>
    <eLiterals name="ak_aggregate" value="1"/>
    <eLiterals name="ak_composite" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//GeneralizableElement #//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" lowerBound="2"
        upperBound="-1" eType="#//AssociationEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//StructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationEnd" eType="#//AssociationEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="BehavioralFeature" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ParameterDirectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavioralFeature" eType="#//BehavioralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterDirectionKind">
    <eLiterals name="pdk_in"/>
    <eLiterals name="pdk_inout" value="1"/>
    <eLiterals name="pdk_out" value="2"/>
    <eLiterals name="pdk_return" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//BehavioralFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concurrency" eType="#//CallConcurrencyKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CallConcurrencyKind">
    <eLiterals name="cck_sequential"/>
    <eLiterals name="cck_guarded" value="1"/>
    <eLiterals name="cck_concurrent" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//BehavioralFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="#//ProcedureExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationClass" eSuperTypes="#//Association #//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abstraction" eSuperTypes="#//Dependency">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapping" eType="#//MappingExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usage" eSuperTypes="#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//Dependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" lowerBound="1"
        upperBound="-1" eType="#//TemplateArgument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElement" lowerBound="1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
        eType="#//Binding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentLocation" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="residentElement" upperBound="-1"
        eType="#//ElementResidence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" upperBound="-1"
        eType="#//Artifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedComponent" upperBound="-1"
        eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementResidence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//VisibilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resident" lowerBound="1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Permission" eSuperTypes="#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Primitive" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" lowerBound="1"
        upperBound="-1" eType="#//EnumerationLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" lowerBound="1"
        eType="#//Enumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgrammingLanguageDataType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="#//TypeExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        upperBound="-1" eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkEnd" upperBound="-1"
        eType="#//LinkEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" upperBound="-1" eType="#//AttributeLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" eType="#//ComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInstance" upperBound="-1"
        eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLink" upperBound="-1"
        eType="#//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkEnd" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" lowerBound="1"
        eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1" eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationEnd" lowerBound="1"
        eType="#//AssociationEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiedValue" upperBound="-1"
        eType="#//AttributeLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="1"
        eType="#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" lowerBound="2"
        upperBound="-1" eType="#//LinkEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeLink" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkEnd" eType="#//LinkEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" eSuperTypes="#//Instance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeInstance" eType="#//NodeInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resident" upperBound="-1"
        eType="#//Instance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeInstance" eSuperTypes="#//Instance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resident" upperBound="-1"
        eType="#//ComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recurrence" eType="#//IterationExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="#//ObjectSetExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAsynchronous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="script" eType="#//ActionExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualArgument" upperBound="-1"
        eType="#//Argument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionSequence" eType="#//ActionSequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionSequence" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantiation" lowerBound="1"
        eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DestroyAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="UninterpretedAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//Instance"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkObject" eSuperTypes="#//Object #//Link"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataValue" eSuperTypes="#//Instance"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reception" eSuperTypes="#//BehavioralFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="TerminateAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stimulus" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
        eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
        eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicationLink" eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dispatchAction" lowerBound="1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exception" eSuperTypes="#//Signal"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubsystemInstance" eSuperTypes="#//Instance"/>
  <eClassifiers xsi:type="ecore:EClass" name="UseCase" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extend" upperBound="-1"
        eType="#//Extend"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="include" upperBound="-1"
        eType="#//Include"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionPoint" upperBound="-1"
        eType="#//ExtensionPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extend" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="#//BooleanExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1" eType="#//UseCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" lowerBound="1"
        eType="#//UseCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionPoint" lowerBound="1"
        upperBound="-1" eType="#//ExtensionPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionPoint" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useCase" lowerBound="1"
        eType="#//UseCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Include" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="addition" lowerBound="1"
        eType="#//UseCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1" eType="#//UseCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="UseCaseInstance" eSuperTypes="#//Instance"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="top" lowerBound="1" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submachineState" upperBound="-1"
        eType="#//SubmachineState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//StateVertex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deferrableEvent" upperBound="-1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalTransition" upperBound="-1"
        eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doActivity" eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateVertex" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//CompositeState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConcurrent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subvertex" upperBound="-1"
        eType="#//StateVertex"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//Guard"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effect" eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//StateVertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//StateVertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="#//BooleanExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="1"
        eType="#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubmachineState" eSuperTypes="#//CompositeState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="submachine" lowerBound="1"
        eType="#//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="when" eType="#//TimeExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeExpression" eType="#//BooleanExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pseudostate" eSuperTypes="#//StateVertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//PseudostateKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PseudostateKind">
    <eLiterals name="pk_choice"/>
    <eLiterals name="pk_deepHistory" value="1"/>
    <eLiterals name="pk_fork" value="2"/>
    <eLiterals name="pk_initial" value="3"/>
    <eLiterals name="pk_join" value="4"/>
    <eLiterals name="pk_junction" value="5"/>
    <eLiterals name="pk_shallowHistory" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="SynchState" eSuperTypes="#//StateVertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StubState" eSuperTypes="#//StateVertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Collaboration" eSuperTypes="#//GeneralizableElement #//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" upperBound="-1"
        eType="#//Interaction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representedClassifier"
        eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representedOperation" eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainingElement" upperBound="-1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedCollaboration" upperBound="-1"
        eType="#//Collaboration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
        upperBound="-1" eType="#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//Collaboration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" lowerBound="1"
        eType="#//Interaction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activator" eType="#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
        eType="#//ClassifierRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="#//ClassifierRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" upperBound="-1"
        eType="#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicationConnection"
        eType="#//AssociationRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conformingStimulus" upperBound="-1"
        eType="#//Stimulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierRole" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1" upperBound="-1"
        eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableFeature" upperBound="-1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableContents" upperBound="-1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conformingInstance" upperBound="-1"
        eType="#//Instance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationRole" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" upperBound="-1"
        eType="#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conformingLink" upperBound="-1"
        eType="#//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationEndRole" eSuperTypes="#//AssociationEnd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collaborationMultiplicity"
        eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//AssociationEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableQualifier" upperBound="-1"
        eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionInstanceSet" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//CollaborationInstanceSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" eType="#//Interaction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingStimulus"
        lowerBound="1" upperBound="-1" eType="#//Stimulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationInstanceSet" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactionInstanceSet"
        upperBound="-1" eType="#//InteractionInstanceSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collaboration" eType="#//Collaboration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingInstance"
        lowerBound="1" upperBound="-1" eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingLink" upperBound="-1"
        eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainingElement" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityGraph" eSuperTypes="#//StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partition" upperBound="-1"
        eType="#//Partition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partition" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityGraph" lowerBound="1"
        eType="#//ActivityGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubactivityState" eSuperTypes="#//SubmachineState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDynamic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamicArguments" eType="#//ArgListsExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamicMultiplicity" eType="#//Multiplicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionState" eSuperTypes="#//SimpleState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDynamic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamicArguments" eType="#//ArgListsExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamicMultiplicity" eType="#//Multiplicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallState" eSuperTypes="#//ActionState"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectFlowState" eSuperTypes="#//SimpleState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSynch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierInState" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inState" lowerBound="1"
        upperBound="-1" eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//GeneralizableElement #//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementImport" upperBound="-1"
        eType="#//ElementImport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//VisibilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSpecification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedElement" lowerBound="1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subsystem" eSuperTypes="#//Package #//Classifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInstantiable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
